const Sequelize = require('sequelize')
const dbConfig = require ('../config/database')

//importação dos models
const Supplier = require('../model/Supplier')
const Product = require('../model/Product')
const User = require('../model/User')
const Equipment = require('../model/Equipment')
const SupplierProduct = require('../model/SupplierProduct')
const Move = require('../model/Move')
const MoveItens = require('../model/MoveItens')
const LoteItens = require('../model/LoteItens')
const MoveItensVolume = require('../model/MoveItensVolume')
const Analysis = require('../model/Analysis')
const AnalysisData = require('../model/AnalysisData')
const VolumeItensTables = require('../model/VolumeItensTable')
const Devolucao = require('../model/Devolucao')
const DevolucaoItens = require('../model/DevolucaoItens')
const Producao = require('../model/Producao')
const ProducaoEquipment = require('../model/ProducaoEquipment')
const ProducaoItens = require('../model/ProducaoItens')
const Config = require('../model/Config')

const connection = new Sequelize(dbConfig)


Supplier.init(connection)
Config.init(connection)
VolumeItensTables.init(connection)
Product.init(connection)
User.init(connection)
Equipment.init(connection) 
SupplierProduct.init(connection)
Move.init(connection)
MoveItens.init(connection)
LoteItens.init(connection)
MoveItensVolume.init(connection)
Analysis.init(connection)
AnalysisData.init(connection)
Devolucao.init(connection)
DevolucaoItens.init(connection)
Producao.init(connection)
ProducaoEquipment.init(connection)
ProducaoItens.init(connection)

VolumeItensTables.associate(connection.models)
SupplierProduct.associate(connection.models)
LoteItens.associate(connection.models)
Move.associate(connection.models)
MoveItens.associate(connection.models)
MoveItensVolume.associate(connection.models)
Analysis.associate(connection.models)
AnalysisData.associate(connection.models)
Devolucao.associate(connection.models)
DevolucaoItens.associate(connection.models)
Producao.associate(connection.models)
ProducaoEquipment.associate(connection.models)
ProducaoItens.associate(connection.models)


module.exports = connection