const express = require('express')
const routes = express.Router()

const UserRoutes = require('./routes/UserRoutes')
const SupplierRoutes = require('./routes/SupplierRoutes')
const ProductRoutes = require('./routes/ProductRoutes')
const SupplierProductRoutes = require('./routes/SupplierProductRoutes')
const EquipmentRoutes = require('./routes/EquipmentRoutes')
const MoveRoutes = require('./routes/MoveRoutes')
const MoveItensRoutes = require('./routes/MoveItensRoutes')
const MoveItensVolumeRoutes = require('./routes/MoveItensVolumeRoutes')
const LoteRoutes = require('./routes/LoteRoutes')
const VolumeItensTableRoutes = require('./routes/VolumeItensTableRoutes')
const AnalysisRoutes = require('./routes/AnalysisRoutes')
const AnalysisDataRoutes = require('./routes/AnalysisDataRoutes')
const ProducaoRoutes = require('./routes/ProducaoRoutes')
const ProducaoItensRoutes = require('./routes/ProducaoItensRoutes')
const ProducaoEquipamentoRoutes = require('./routes/ProducaoEquipamentoRoutes')
const ConfigRoutes = require('./routes/ConfigRoutes')
const DevolucaoRoutes = require('./routes/DevolucaoRoutes')
const LoginRoutes = require('./routes/LoginRoutes')

const auth = require('./middlewares/auth')

routes.use('/users', UserRoutes)
routes.use('/suppliers',  SupplierRoutes)
routes.use('/products',  ProductRoutes)
routes.use('/suppliers-products',  SupplierProductRoutes)
routes.use('/equipment',  EquipmentRoutes)
routes.use('/moves',  MoveRoutes)
routes.use('/move-itens',  MoveItensRoutes)
routes.use('/move-itens-volumes',  MoveItensVolumeRoutes)
routes.use('/lotes',  LoteRoutes)
routes.use('/volume-itens-tables',  VolumeItensTableRoutes)
routes.use('/analyses',  AnalysisRoutes)
routes.use('/analysis-data',  AnalysisDataRoutes)
routes.use('/producoes',  ProducaoRoutes)
routes.use('/producao-itens',  ProducaoItensRoutes)
routes.use('/producao-equipamentos',  ProducaoEquipamentoRoutes)
routes.use('/config',  ConfigRoutes)
routes.use('/devolucoes',  DevolucaoRoutes)
routes.use('/login', LoginRoutes)

module.exports = routes;