const express = require('express')
const routes = express.Router()

const UserRoutes = require('./routes/UserRoutes')
const SupplierRoutes = require('./routes/SupplierRoutes')
const ProductRoutes = require('./routes/ProductRoutes')
const SupplierProductRoutes = require('./routes/SupplierProductRoutes')
const EquipmentRoutes = require('./routes/EquipmentRoutes')
const MoveRoutes = require('./routes/MoveRoutes')
const MoveItensRoutes = require('./routes/MoveItensRoutes')
const MoveItensVolumeRoutes = require('./routes/MoveItensVolumeRoutes')
const LoteRoutes = require('./routes/LoteRoutes')
const VolumeItensTableRoutes = require('./routes/VolumeItensTableRoutes')
const AnalysisRoutes = require('./routes/AnalysisRoutes')
const AnalysisDataRoutes = require('./routes/AnalysisDataRoutes')
const ProducaoRoutes = require('./routes/ProducaoRoutes')
const ProducaoItensRoutes = require('./routes/ProducaoItensRoutes')
const ProducaoEquipamentoRoutes = require('./routes/ProducaoEquipamentoRoutes')
const ConfigRoutes = require('./routes/ConfigRoutes')
const DevolucaoRoutes = require('./routes/DevolucaoRoutes')
const LoginRoutes = require('./routes/LoginRoutes')

const auth = require('./middlewares/auth')

routes.use('/users', UserRoutes)
routes.use('/suppliers', auth, SupplierRoutes)
routes.use('/products', auth, ProductRoutes)
routes.use('/suppliers-products', auth, SupplierProductRoutes)
routes.use('/equipment', auth, EquipmentRoutes)
routes.use('/moves', auth, MoveRoutes)
routes.use('/move-itens', auth, MoveItensRoutes)
routes.use('/move-itens-volumes', auth, MoveItensVolumeRoutes)
routes.use('/lotes', auth, LoteRoutes)
routes.use('/volume-itens-tables', auth, VolumeItensTableRoutes)
routes.use('/analyses', auth, AnalysisRoutes)
routes.use('/analysis-data', auth, AnalysisDataRoutes)
routes.use('/producoes', auth, ProducaoRoutes)
routes.use('/producao-itens', auth, ProducaoItensRoutes)
routes.use('/producao-equipamentos', auth, ProducaoEquipamentoRoutes)
routes.use('/config', auth, ConfigRoutes)
routes.use('/devolucoes', auth, DevolucaoRoutes)
routes.use('/login', LoginRoutes)

module.exports = routes;